M48
; DRILL file {KiCad 9.0.6} date 2026-03-22T20:09:35+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-22T20:09:35+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.000
%
G90
G05
T1
X133.58Y-89.87
T2
X118.25Y-86.65
X118.25Y-89.19
T3
X118.3Y-91.7
X118.3Y-94.24
T4
X136.3Y-87.97
X136.3Y-90.51
X136.3Y-93.05
M30
