M48
; DRILL file {KiCad 9.0.6} date 2026-03-18T23:30:44+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-18T23:30:44+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X129.9Y-121.45
X131.0Y-61.25
X173.3Y-61.65
X173.4Y-121.25
M30
