M48
; DRILL file {KiCad 9.0.6} date 2026-03-27T12:53:43+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-27T12:53:43+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.000
%
G90
G05
T1
X141.2Y-70.4
X161.701Y-60.668
T2
X145.2Y-62.5
X145.2Y-65.04
X145.2Y-67.58
T3
X137.5Y-59.18
X137.5Y-61.72
X137.5Y-66.66
X137.5Y-69.2
T4
X161.15Y-62.25
X161.15Y-64.79
X161.15Y-67.33
M30
